### PR TITLE
Dmm/improve tests

### PR DESCRIPTION
**Pull request by diegomillan**
@felipemontoya

### CODE REVIEW

**Comment by diegomillan** [comment]
@felipemontoya Finally, I was able to succesfully run tests. There are just a few of these, but I will be moving forward faster since I understood how I should be mocking missing dependencies. Could you take a look at  `test_post_preregistered_user` ,  since the upcoming tests are going to have a similar estructure.

**Comment by felipemontoya** [comment]
@diegomillan I think the structure is fine. It allows you to separate a section of code under your conditions, and run it. Perfect, now lets raise the coverage!

**Comment by jfavellar90** [comment]
Interesting trick to mock not existing imports :+1:

**Comment by felipemontoya** [comment]
What is the status of this PR?

**Comment by diegomillan** [comment]
I think we should merge this ASAP because I need to rebase for the upcoming. Also I have another branch with more tests but I need to change some of them

**Comment by felipemontoya** [comment]
Ok, you should have mentioned this before, so we could take a look after your 'a7e37c8' commit

**Comment by felipemontoya** [comment]
I see you raised the coverage froma global 14% to a global 22% :+1:  for that. We can merge this and continue the work in a new PR

**Comment by diegomillan** [comment]
Awesome, lets merge this in order to rebase and raise a little bit more the coverage

**Comment by diegomillan** [comment]
Could you approve this @felipemontoya ???

**Pull request merged**
