### PR TITLE
Dmm/fix email templates

### PR DESCRIPTION
**Pull request by diegomillan**
@jfavellar90 @felipemontoya

### CODE REVIEW

**Comment by jfavellar90** [comment]
:+1:

**Comment by felipemontoya** [comment]
Where does `emails/activation_email.html` exist?

**Comment by diegomillan** [comment]
@felipemontoya [here](https://github.com/eduNEXT/openedx-email-extensions/blob/master/openedx_email_extensions/templates/emails/activation_email.html)

**Comment by felipemontoya** [comment]
Ok, I was looking for it in the core repo. Thanks. Also :+1:

**Pull request merged**
