### PR TITLE
adding compatibility with ficus grade app

### PR DESCRIPTION
**Pull request by diegomillan**
@felipemontoya 
@jfavellar90

### CODE REVIEW

**Comment by jfavellar90** [comment]
This is a fix that avoids the import failure by using the new grades module in Ficus, but we have not tested yet if this is working properly to get grades reports. I think we can use this version only for ficus testing purposes, not as a functional version

**Comment by diegomillan** [comment]
I agree. Should I use the merge commit SHA to bump it,  or a new tag like "ficus first compatible version" @jfavellar90 @felipemontoya ????

**Comment by felipemontoya** [comment]
@diegomillan to install it into the edunext-platform you can use the commit SHA for now

**Comment by jfavellar90** [comment]
:+1: :+1:

**Pull request merged**
