### PR TITLE
First step towards having testing in edunext-openedx-extensions exter…

### PR DESCRIPTION
**Pull request by jfavellar90**
In this PR I'm integrating this repo with circle CI
@diegomillan 
@felipemontoya

### CODE REVIEW

**Comment by felipemontoya** [comment]
Are you planning to fix all the pylint issues to get this merged? There are around 240 issues. Adding some dependencies just for testing (like django_rest_framework) will fix about 63. It is not so bad, and it would eliminate the need for diff-quality

**Comment by jfavellar90** [comment]
I would like to discuss about pylint and ask some questions:

- We still have a lot of import errors because of the core edx-platform modules. How could we fix this? allow a maximum number of pylint errors as edx does?

- I was fixing no-self-use and unused-argument errors by adding comments to bypass the validations, but I think these errors should be corrected by refactoring a bit the code

- Should we use the text formatting in logs in the way pylint proposes (Use % formatting in logging functions and pass the % parameters as arguments), or using the format method for python strings is still acceptable?

@felipemontoya 
@diegomillan

**Comment by jfavellar90** [comment]
Now the build is ok, I'm going to test this with edunext-platform to verify it's working as expected

**Comment by jfavellar90** [comment]
Tested in dev environment and working ok. Should we bump the version?
@felipemontoya 
@diegomillan

**Comment by felipemontoya** [comment]
We don't gain anything now by bumping, but we can merge this now :+1:

**Pull request merged**
