### PR TITLE
Fi/ednx/lc

### PR DESCRIPTION
**Pull request by jfavellar90**
This is a WIP, but I open the PR to start the conversation. Basically I'm adding 4 new modules to the external application: edraak_i18n, microsite_aware_functions, ednx_lang_pref and dark_lang, the first two created by edunext, the last two extracted from edx-platform core. The reason for this is we will modify these modules, so better isolate them and support our changes in our external app.

@felipemontoya 
@diegomillan

### CODE REVIEW

**Comment by felipemontoya** [comment]
I think we will eventually merge this 4 modules into 1 or 2, but for now, we want to keep being compatible without too much changes. :+1: 

Also @jfavellar90 you need to ignore the migrations directory in the pep8 configuration. I suggest that you move it at the same time into the setup.cfg file. [like this](http://stackoverflow.com/questions/30304409/how-to-write-a-pep8-configuration-pep8-rc-file).

**Comment by felipemontoya** [comment]
The module microsite_aware_functions also has a enrollments module which we should bring here at the same time

**Comment by felipemontoya** [comment]
Just for reference. Here is the PR at the edx-platform code https://github.com/eduNEXT/edunext-platform/pull/128

**Comment by felipemontoya** [comment]
How are we on this front, is this PR ready? can we squash the commits into something more logical and merge? or are we still waiting for something?

**Comment by jfavellar90** [comment]
Filtering enrollments is working for mobile API

**Pull request merged**
